package com.test;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.BeanFieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.fieldgroup.PropertyId;
import com.vaadin.data.util.ObjectProperty;
import com.vaadin.data.util.PropertysetItem;
import com.vaadin.data.validator.StringLengthValidator;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;

public class FormUI extends CustomComponent {

	private static final long serialVersionUID = -1384748160629976463L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	
	private TextField firstname;	
	private TextField lastname;
	private OptionGroup gender;
	private TextArea whyapply;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public FormUI(UI parent) {
		mainLayout = new VerticalLayout();
		mainLayout.setSpacing(true);
		mainLayout.setSizeFull();
		setCompositionRoot(mainLayout);

		firstname = new TextField("First name");
		firstname.setRequired(true);
		lastname = new TextField("Last name");
		lastname.setRequired(true);
		
		gender = new OptionGroup("Gender");
		gender.addItem("Female");
		gender.addItem("Male");
		gender.setMultiSelect(false);
		gender.select("Female");
		
		whyapply = new TextArea("Why are you applying to this job");
		whyapply.setRows(10);
		whyapply.setWordwrap(true);
		
		Button submit = new Button("Submit");
		submit.addClickListener(new Button.ClickListener() {			
			
			@Override
			public void buttonClick(ClickEvent event) {
			}
		});
		
		mainLayout.addComponent(firstname);
		mainLayout.addComponent(lastname);
		mainLayout.addComponent(gender);
		mainLayout.addComponent(whyapply);
		mainLayout.addComponent(submit);
	}
}
